#!/usr/bin/env python3

import sys
import os
import helpers

from analyzer import Analyzer
from termcolor import colored


def main():

    # ensure proper usage
    if len(sys.argv) != 2 or sys.argv[1][0] != "@":
        sys.exit("Usage: ./tweets @screen_name")

    # get tweets using user name without "@""
    tweets = helpers.get_user_timeline(sys.argv[1][1:], 50)

    # check if succesfull
    if tweets is None:
        print("Can't get tweets!")
        sys.exit(1)

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze tweets and print results
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("%2d" % score + " " + tweet, "green"))
        elif score < 0.0:
            print(colored("%2d" % score + " " + tweet, "red"))
        else:
            print(colored("%2d" % score + " " + tweet, "yellow"))

if __name__ == "__main__":
    main()
